/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumTicketStatus } from "./EnumTicketStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";
import { AttachmentCreateNestedManyWithoutTicketsInput } from "./AttachmentCreateNestedManyWithoutTicketsInput";
import { CommentCreateNestedManyWithoutTicketsInput } from "./CommentCreateNestedManyWithoutTicketsInput";

@InputType()
class TicketCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumTicketStatus,
  })
  @IsEnum(EnumTicketStatus)
  @IsOptional()
  @Field(() => EnumTicketStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => AttachmentCreateNestedManyWithoutTicketsInput,
  })
  @ValidateNested()
  @Type(() => AttachmentCreateNestedManyWithoutTicketsInput)
  @IsOptional()
  @Field(() => AttachmentCreateNestedManyWithoutTicketsInput, {
    nullable: true,
  })
  attachments?: AttachmentCreateNestedManyWithoutTicketsInput;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutTicketsInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutTicketsInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutTicketsInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutTicketsInput;
}

export { TicketCreateInput as TicketCreateInput };
